version: '3.8'

services:
  netflix-code-bot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/usr/src/app/logs
      - whatsapp-sessions:/usr/src/app/.wwebjs_auth
    networks:
      - netflix-bot-network

volumes:
  whatsapp-sessions:

networks:
  netflix-bot-network:
    driver: bridge 